// <auto-generated />
using System;
using DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DAL.Migrations
{
    [DbContext(typeof(PastaBINContext))]
    [Migration("20240529121655_test3")]
    partial class test3
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Model.Cook", b =>
                {
                    b.Property<int>("CookID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CookID"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CookID");

                    b.HasIndex("Login")
                        .IsUnique();

                    b.ToTable("Cooks");
                });

            modelBuilder.Entity("Model.PastaGroupSharing", b =>
                {
                    b.Property<int>("GroupSharingID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GroupSharingID"));

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeleteTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("GroupKey")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PastaBindID")
                        .HasColumnType("int");

                    b.HasKey("GroupSharingID");

                    b.HasIndex("PastaBindID");

                    b.ToTable("PastaGroupSharing");
                });

            modelBuilder.Entity("Model.PastaHistory", b =>
                {
                    b.Property<int>("HistoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HistoryID"));

                    b.Property<int>("CookID")
                        .HasColumnType("int");

                    b.Property<int>("PastaBindID")
                        .HasColumnType("int");

                    b.Property<DateTime>("VisitDate")
                        .HasColumnType("datetime2");

                    b.HasKey("HistoryID");

                    b.HasIndex("CookID");

                    b.HasIndex("PastaBindID");

                    b.ToTable("PastaHistory");
                });

            modelBuilder.Entity("Model.PastaImage", b =>
                {
                    b.Property<int>("ImageID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ImageID"));

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("ImageData")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("PastaBindID")
                        .HasColumnType("int");

                    b.HasKey("ImageID");

                    b.ToTable("PastaImage");
                });

            modelBuilder.Entity("Model.PastaSharingSettings", b =>
                {
                    b.Property<int>("SharingSettingsID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SharingSettingsID"));

                    b.Property<int>("CookID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("EndSharingDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("PastaBindID")
                        .HasColumnType("int");

                    b.HasKey("SharingSettingsID");

                    b.HasIndex("CookID");

                    b.HasIndex("PastaBindID")
                        .IsUnique();

                    b.ToTable("PastaSharingSettings");
                });

            modelBuilder.Entity("Model.PastaTxt", b =>
                {
                    b.Property<int>("PastaTxtID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PastaTxtID"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DeleteDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.HasKey("PastaTxtID");

                    b.ToTable("PastaTxt");
                });

            modelBuilder.Entity("PastaBind", b =>
                {
                    b.Property<int>("PastaBindID")
                        .HasColumnType("int");

                    b.Property<int>("CookID")
                        .HasColumnType("int");

                    b.Property<string>("GlobalKey")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("PastaID")
                        .HasColumnType("int");

                    b.Property<int>("SharingSettingsID")
                        .HasColumnType("int");

                    b.HasKey("PastaBindID");

                    b.HasIndex("CookID");

                    b.HasIndex("GlobalKey")
                        .IsUnique();

                    b.ToTable("PastaBinds");
                });

            modelBuilder.Entity("Model.PastaGroupSharing", b =>
                {
                    b.HasOne("PastaBind", "PastaBind")
                        .WithMany("GroupSharing")
                        .HasForeignKey("PastaBindID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PastaBind");
                });

            modelBuilder.Entity("Model.PastaHistory", b =>
                {
                    b.HasOne("Model.Cook", "Cook")
                        .WithMany("Histories")
                        .HasForeignKey("CookID")
                        .IsRequired();

                    b.HasOne("PastaBind", "PastaBind")
                        .WithMany("Histories")
                        .HasForeignKey("PastaBindID")
                        .IsRequired();

                    b.Navigation("Cook");

                    b.Navigation("PastaBind");
                });

            modelBuilder.Entity("Model.PastaSharingSettings", b =>
                {
                    b.HasOne("Model.Cook", "Cook")
                        .WithMany("SharingSettings")
                        .HasForeignKey("CookID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PastaBind", "PastaBind")
                        .WithOne("SharingSettings")
                        .HasForeignKey("Model.PastaSharingSettings", "PastaBindID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cook");

                    b.Navigation("PastaBind");
                });

            modelBuilder.Entity("PastaBind", b =>
                {
                    b.HasOne("Model.Cook", "Cook")
                        .WithMany("PastaBinds")
                        .HasForeignKey("CookID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Model.PastaImage", "Image")
                        .WithOne("PastaBind")
                        .HasForeignKey("PastaBind", "PastaBindID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Model.PastaTxt", "Pasta")
                        .WithOne("PastaBind")
                        .HasForeignKey("PastaBind", "PastaBindID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cook");

                    b.Navigation("Image");

                    b.Navigation("Pasta");
                });

            modelBuilder.Entity("Model.Cook", b =>
                {
                    b.Navigation("Histories");

                    b.Navigation("PastaBinds");

                    b.Navigation("SharingSettings");
                });

            modelBuilder.Entity("Model.PastaImage", b =>
                {
                    b.Navigation("PastaBind")
                        .IsRequired();
                });

            modelBuilder.Entity("Model.PastaTxt", b =>
                {
                    b.Navigation("PastaBind")
                        .IsRequired();
                });

            modelBuilder.Entity("PastaBind", b =>
                {
                    b.Navigation("GroupSharing");

                    b.Navigation("Histories");

                    b.Navigation("SharingSettings")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
